config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index]
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index] do
    get :current, on: :collection
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :rule, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success')
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :description, :value)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def current
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  BADGE_LIST = {
    'Пройти тест с первого раза' => :first_try,
    'Пройти все тесты определенной категории' => :all_tests_by_category,
    'Пройти все тесты определенного уровня' => :all_tests_by_level
  }.freeze
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= badge.image %></td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.description %></td>
  <td class="align-middle">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to t('.show'),
                  admin_badge_path(badge),
                  class: 'btn btn-outline-secondary' %>
      <%= link_to t('.edit'),
                  edit_admin_badge_path(badge),
                  class: 'btn btn-outline-secondary' %>
      <%= link_to t('.delete'),
                  admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: t('.confirm')},
                  class: 'btn btn-outline-secondary' %>
    </div>
  </td>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |f| %>
  <div class="form-group col-md-8">
    <%= render "shared/errors", resource: @badge %>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title, id: :badge_title, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :image %>
      <%= f.text_field :image, id: :badge_image, placeholder: "badge1.png", class: 'form-control' %>
    </p>

    <p>
      <%= f.label :rule %>
      <%= f.select :rule, options_for_select(BadgesHelper::BADGE_LIST), { include_blank: t('.rule') }, class: 'form-control' %>
    </p>
    
    <p>
      <%= f.label :value %>
      <%= f.text_field :value, id: :value, class: 'form-control' %>
    </p>

    <p>
      <button class="btn btn-outline-info" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <%= t('.info_buttopn') %>
      </button>
    </p>
    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <p><%= t('.info') %></p>
      </div>
    </div>

    <p>
      <%= f.label :description %>
      <%= f.text_area :description, id: :badge_description, rows: 7, cols: 60, class: 'form-control' %>
    </p>

    <%= f.submit class: 'btn btn-success btn-lg mt-2' %>
  </div>
<% end %> 

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1 class="display-4 text-center"><%= t('.header', title: @badge.title) %></h1>

    <div class="card border-success rounded mb-3 mt-4">
      <div class="card-body">

        <%= render "form" %>

        <p>
          <%= link_to t('.back'), admin_badge_path(@badge), class: 'btn btn-secondary btn-sm float-right' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row mt-3">
  <div class="col col-md">
    <h1 class="display-4 text-center"><%= t('.header') %></h1>
    <table class="table table-hover text-center mt-3">
      <thead>
      <tr>
        <th scope="col"><%= t('.title') %></th>
        <th scope="col"><%= t('.image') %></th>
        <th scope="col"><%= t('.rule') %></th>
        <th scope="col"><%= t('.description') %></th>
        <th scope="col" colspan="3"><%= t('.actions') %></th>
      </tr>
      </thead>

      <tbody>
        <%= render @badges %>
      </tbody>
    </table>

    <p>
      <%= link_to t('.new_badge'), new_admin_badge_path, class: 'btn btn-success btn-lg' %>
    </p>

    <p>
      <%= link_to t('.back'), admin_tests_path, class: 'btn btn-secondary btn-block' %>
    </p>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1 class="display-4 text-center"><%= t('.header') %></h1>

    <div class="card border-success rounded mb-3 mt-4">
      <div class="card-body">

        <%= render "form" %>

        <p>
          <%= link_to t('.back'), admin_badges_path, class: 'btn btn-secondary btn-sm float-right' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1 class="display-4 text-center"><%= t('.header') %></h1>

    <div class="card border-secondary rounded mb-3 mt-4">
      <div class="card-body">
        <p>
          <strong><%= t('.title') %></strong>
          <%= @badge.title %>
        </p>

        <p>
          <strong><%= t('.image') %></strong>
          <%= @badge.image %>
        </p>

        <p>
          <strong><%= t('.rule') %></strong>
          <%= @badge.rule %>
        </p>

        <p>
          <strong><%= t('.description') %></strong>
          <%= @badge.description %>
        </p>

        <p>
          <%= link_to t('.edit'), edit_admin_badge_path(@badge), class: 'btn btn-primary btn-sm active' %> 
          <%= link_to t('.back'), admin_badges_path, class: 'btn btn-secondary btn-sm active' %>
        </p>
      </div>
    </div>
  </div>
</div>