config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index]
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index] do
    get :current, on: :collection
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_count_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_count_answers
    errors.add(:answers_maximum, 'four answers is the maximum') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :rule, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  def url
    "https://gist.github.com/#{github_id}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true,
                    uniqueness: { scope: :level }

  validates :level, :timer, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :with_questions, -> { joins(:questions).group('tests.id') }

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :by_level, ->(level) { where(level: level) }

  scope :by_category_title, ->(category_title) { joins(:category).where(categories: { title: category_title }) }

  def self.sort_by(category_title)
    by_category_title(category_title).order(title: :desc).pluck(:title)
  end

  def timer_value_positive?
    timer.positive?
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  scope :completed_successfully, -> { where(completed_successfully: true) }

  def completed?
    current_question.nil?
  end

  def timeout?
    Time.zone.now > completion_time
  end

  def success_percent
    correct_questions.to_f / test.questions.size * 100
  end

  def success?
    success_percent >= SUCCESS_PERCENT
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completion_time
    created_at + self.test.timer.seconds
  end

  def time_left
    (completion_time - Time.zone.now).to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    answer_ids ||= []
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test', foreign_key: :user_id, dependent: :destroy

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  def sort_by(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def tests_passed(test_ids)
    test_passages.completed_successfully.where(test_id: test_ids).map(&:test_id).uniq.sort
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def current
    @badges = current_user.badges
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: :start

  def index
    @tests = Test.with_questions
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test), notice: t('.after_start_greeting')
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_status(answer)
    answer.correct ? t('.correct_answer') : t('.wrong_answer')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.now.year
  end

  def current_time
    I18n.l(Time.current, format: :short)
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  BADGE_LIST = {
    'Пройти тест с первого раза' => :first_try,
    'Пройти все тесты определенной категории' => :all_tests_by_category,
    'Пройти все тесты определенного уровня' => :all_tests_by_level
  }.freeze
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def test_complete_message(test_passage)
    test_passage.success? ? t('.test_pass_success') : t('.test_pass_fail')
  end

  def color_border(test_passage)
    test_passage.success? ? 'success' : 'danger'
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def questions_count(test)
    test.questions.count
  end

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end

  def test_timer(test)
    test.timer.to_f / 60
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary">
  <h1 class="testguru-logo">
    <%= link_to t('.testguru_welcome'), root_path %>
  </h1>


  <span class="navbar-text">
    <%= link_to t('.admin'), admin_tests_path, class: 'btn btn-outline-warning' %>
    <%= octicon 'clock' %>
    <%= t('.login_time') %>
    <%= current_time %> |
    <%= octicon 'person' %>
    <%= t('.profile', email: current_user.email) %> |
    <%= octicon 'sign-out' %>
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
  </span>
</nav>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by Babitsky Alexandr under the leadership of <%= link_to 'Thinknetica', 'https://thinknetica.com' %> in <%= current_year %>
     <p>Project model: <%= link_to (octicon 'logo-github', height: 15), 'https://github.com/TailsSavarin/test-guru' %></p>
  </small>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">
  <h1 class="testguru-logo">
    <%= link_to t('.testguru_welcome'), root_path %>
  </h1>

  <span class="navbar-text">
    <% if current_user&.admin? %>
      <%= link_to t('.admin'), admin_tests_path, class: 'btn btn-outline-warning' %>
    <% end %> 

    <% if user_signed_in? %>
      <%= octicon 'clock' %>
      <%= t('.login_time') %>
      <%= current_time %>
      <%= link_to t('.my_badges'), current_badges_path, class: 'btn btn-outline-info' %>
      <%= link_to t('.contact'), new_feedback_path, class: 'btn btn-outline-primary' %>
      <%= octicon 'person' %>
      <%= t('.profile', email: current_user.email) %>
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path, class: 'btn btn-outline-primary' %>
      <%= link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-outline-success' %> 
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "admin/nav" %>

    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <% bs_class = key == 'alert' ? 'danger' : 'primary' %>

  <div class="alert alert-<%= bs_class %> alert-dismissible fade show mt-3" role="alert">
    <strong><%= message %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>