config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index]
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index] do
    get :current, on: :collection
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :rule, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success')
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :description, :value)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def current
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  BADGE_LIST = {
    'Пройти тест с первого раза' => :first_try,
    'Пройти все тесты определенной категории' => :all_tests_by_category,
    'Пройти все тесты определенного уровня' => :all_tests_by_level
  }.freeze
end

app/views/badges/_badge.html.erb
<ul class="list-unstyled">
  <li class="media">
    <img src="/assets/badges/<%= badge.image %>" class="mr-3" alt="badge image">
    <div class="media-body">
      <h5 class="mt-0 mb-1"><%= badge.title %></h5>
      <%= badge.description %>
    </div>
  </li>
</ul>

app/views/badges/current.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1 class="display-4 text-center"><%= t('.header') %></h1>

    <% if @badges.present? %>  
      <%= render @badges %>
    <% else %>
      <h3 class="text-center"><%= t('.no_badges') %></h3>
    <% end %>

    <p>
      <%= link_to t('.badge_list'), badges_path, class: 'btn btn-primary btn-sm active' %>
      <%= link_to t('.back'), tests_path, class: 'btn btn-secondary btn-sm active' %>
    </p>
  </div>
</div>

app/views/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1 class="display-4 text-center"><%= t('.header') %></h1>

    <%= render @badges %>

    <p>
      <%= link_to t('.current_badges'), current_badges_path, class: 'btn btn-primary btn-sm active' %>
      <%= link_to t('.back'), tests_path, class: 'btn btn-secondary btn-sm active' %>
    </p>
  </div>
</div>