config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index]
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index] do
    get :current, on: :collection
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  scope :completed_successfully, -> { where(completed_successfully: true) }

  def completed?
    current_question.nil?
  end

  def timeout?
    Time.zone.now > completion_time
  end

  def success_percent
    correct_questions.to_f / test.questions.size * 100
  end

  def success?
    success_percent >= SUCCESS_PERCENT
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completion_time
    created_at + self.test.timer.seconds
  end

  def time_left
    (completion_time - Time.zone.now).to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    answer_ids ||= []
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update gist]

  def show; end

  def reult; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.timeout?
      if @test_passage.success?
        @test_passage.update_attributes(completed_successfully: true)
        UserBadgeService.new(@test_passage).badges_unlock
      end
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage), notice: t('.badges')
    else
      render :show
    end
  end

  def gist
    question = @test_passage.current_question
    service = GistQuestionService.new(question)
    result = service.call

    if service.success?
      current_user.gists.create(question: question, github_id: result.id)
      redirect_to @test_passage, notice: t('.success', link: result[:html_url])
    else
      redirect_to @test_passage, alert: t('.failure')
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def test_complete_message(test_passage)
    test_passage.success? ? t('.test_pass_success') : t('.test_pass_fail')
  end

  def color_border(test_passage)
    test_passage.success? ? 'success' : 'danger'
  end
end

app/views/test_passages/_form.html.erb
<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |f| %>
  <div class="form-group">
    <%= f.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
      <div class="form-check label">
        <%= b.check_box id: "answer_ids_#{b.object.id}" %>
        <%= b.label %>
      </div>
    <% end %>

    <%= f.submit t('test_passages.show.next'), class: 'btn btn-info mt-4' %>
  </div>
<% end %>

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-10">
    <h1 class="display-4 text-center"><%= t('.header', title: @test_passage.test.title) %></h1>
    <div class="card border-<%= color_border(@test_passage) %> rounded mb-3 mt-4">
      <h1 class="text-center mt-3"><%= test_complete_message(@test_passage) %></h1> 
      <div class="card-body">
        <% if @test_passage.success? %>
          <div class="alert alert-success" role="alert">
            <h3 class="alert-heading"><%= t('.success', title: @test_passage.test.title) %></h3>
            <p class="mb-0"><%= t('.percent') %> <%= @test_passage.success_percent.to_i %>%</p>
          </div>
        <% else %>
          <div class="alert alert-danger" role="alert">
            <h3 class="alert-heading"><%= t('.failure', title: @test_passage.test.title) %></h3>
            <p class='mb-0'><%= t('.percent') %> <%= @test_passage.success_percent.to_i %>%</p>
          </div>
        <% end %>

        <p>
          <%= link_to t('.back'), tests_path, class: 'btn btn-primary btn-block mt-4' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-10">
    <h1 class="display-4 text-center"><%= t('.header', title: @test_passage.test.title) %></h1>

    <div class="card border-info rounded mb-3 mt-4">
      <div class="alert alert-info text-center">
        <% if @test_passage.test.timer_value_positive? %>
          <h3><%= content_tag :test_timer, t('.loading'),
                              class: 'timer',
                              data: { time: @test_passage.time_left,
                                      test_passage_id: @test_passage.id } %></h3>
        <% end %>
      </div>
      <div class="card-body">
        <p class="text-center">
        <%= t('.question_numbers', first: @test_passage.current_question_number,
                                   second: @test_passage.test.questions.size) %>
        <p>

        <div class="progress">
          <%= content_tag :div,
                          class: 'progress-bar progress-bar-striped progress-bar-animated bg-info',
                          data: { question_number: @test_passage.current_question_number,
                                  questions_count: @test_passage.test.questions.size } do %>
          <% end %>
        </div>

        <h4 class="text-center mt-4">
          <strong><%= @test_passage.current_question.body %></strong>
        </h4>

        <p>
          <strong><%= t('.answers') %></strong>
        </p>
        
        <%= render "form" %>

        <p>
          <%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-outline-info mt-3 float-right' %>
        </p>
      </div>
    </div>
  </div>
</div>